#!/usr/bin/env bash
#script that will display information about subdomains

function get_info {
    local dom=$1
    local subd=$2
    local rec
    local ip
    rec=$(dig "$subd"."$dom" +noall +answer +nocomments | awk '{print $4}')
    ip=$(dig "$subd"."$dom" +noall +answer +nocomments | awk '{print $5}')
    
    echo "The subdomain $subd is a $rec record and points to $ip"
}

dom=$1
subd=$2

get_info "$dom" "$subd"