#!/usr/bin/env bash
#script that will display information about subdomains

function get_info {
    dom=$1
    subd=$2
    rec=$(dig "$subd"."$dom" +noall +answer +nocomments | awk '{print $4}')
    ip=$(dig "$subd"."$dom" +noall +answer +nocomments | awk '{print $5}')
    
    echo "The subdomain $subd is a $rec record and points to $ip"
}

dom=$1

if [ "$#" -ne 2 ]; then
    get_info "$dom" "www"
    get_info "$dom" "lb-01"
    get_info "$dom" "web-01"
    get_info "$dom" "web-02"
else
    subd=$2
    get_info "$dom" "$subd"
fi
