#!/usr/bin/env bash
#script that configures a new Ubuntu machine to respect given requirements
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
