#!/usr/bin/env bash
#script that configures a new Ubuntu machine to respect given requirements
apt-get update
apt-get -y install nginx
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html
service nginx start
