#!/usr/bin/env bash
#script that transfers a file from our client to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

F_PTH="$1"
SRV_IP="$2"
USR="$3"
KEY="$4"

scp -o StrictHostKeyChecking=no -i "$KEY" "$F_PTH" "$USR@$SRV_IP:~/"