#!/usr/bin/env bash
#scripts that loops over 10 iterations: 4 bad luck, 8 is your chance, else Best school
i=1
while ((i <= 10)); do
    echo "Best School"
    if ((i==9))
    then
        echo "Hi"
    fi
    ((i++))
done