#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/myhosts
sed -i 's/localhost$/localhost 127.0.0.2/' ~/myhosts
echo 'facebook 8.8.8.8' >> ~/myhosts
cp -f ~/myhosts /etc/hosts