#!/usr/bin/env bash
# Bash script to reconfigure Nginx so that Nginx
# runs as the nginx user and listens on port
# 8080 on all active IPs

service nginx stop
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/user  www-data;/user  nginx;/' /etc/nginx/nginx.conf
service nginx start
nc -z 0 8080
